version: '3.8'
services:
  react-app:
    build:
      context: ./client
      dockerfile: frontend-prod.dockerfile
    ports:
      - '8081:80'
  node-app:
    build:
      context: ./server
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node app.js
